### ISSUE TITLE
Assessors unable to access Assessments link (00024 DHCJ) 

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/assessments#66]
**Describe the bug**
https://judicial-appointments.slack.com/archives/CSME49V1V/p1602496714187300

https://www.notifications.service.gov.uk/services/0abe6c8e-0b87-4cde-9493-5da4921ccc53/notification/04979021-c220-48bb-a851-1f2ea218c5fc

**Comment by warrensearle** [comment]
@Rebecca-mcknight1991 this was caused by spaces having been used in the email addresses. The data has been cleaned and have created the following tasks to help avoid this happening again:
- Admin#961 Edit IA should trim spaces from email address
- Apply#538 Entering IAs should trim spaces from entered email addresses.
