### ISSUE TITLE
Remove sentry tracking from the assessments-develop environment

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/assessments#76]
We want to remove sentry from the development environment doesn't track errors from the bugs during development.

**Comment by mbrookeswebdev** [comment]
@warrensearle I don't think Sentry is tracking development, this is the code I've found in main.js:

```
if (process.env.NODE_ENV !== 'development') {
  Sentry.init({
    dsn: '[removed]',
    environment: process.env.NODE_ENV,
    release: process.env.npm_package_version,
    integrations: [new Integrations.Vue({ Vue, attachProps: true })],
  });
}
```

**Comment by warrensearle** [comment]
Yes, that's the place.

When we're running the apps on localhost we are using `NODE_ENV = 'development'` - which enables hot reloading and recompiling.
Whenever the site is running on a url, be that production, staging or develop, we are using `NODE_ENV = 'production'`.

We need to include an additional check in there so that Sentry is not initialised for URLS matching `-develop.`

This will mean that Sentry only logs errors from our staging and production servers.
